name: Copilot Usage Tracker
on:
  schedule:
    - cron: '0 12 * * *'  # Daily at 12 PM UTC
  workflow_dispatch:

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Scrape Copilot usage
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          import requests
          from bs4 import BeautifulSoup

          session = requests.Session()
          session.headers = {'Authorization': f'token {env.GH_TOKEN}'}
          response = session.get('https://github.com/settings/copilot')
          soup = BeautifulSoup(response.text, 'html.parser')
          
          # Find usage element (update selector if needed)
          usage_div = soup.select_one('.js-copilot-usage-remaining')
          tokens = usage_div.text.strip().split(' ')[0] if usage_div else 'N/A'
          
          with open('copilot.json', 'w') as f:
              f.write(f'{{"tokens": "{tokens}"}}')
        shell: python

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add copilot.json
          git commit -m "Update Copilot usage"
          git push
